# Site settings

# Name of your site (displayed in the header)
name: Test

# Short bio or description (displayed in the header)
description: Solving frustrating problems with easy solutions

email: nrcraver@gmail.com
url: "https://nickcraver.com"

permalink: pretty
contenturl: "/images/content/"
markdown: kramdown
kramdown:
  input: GFM
  parse_block_html: true
excerpt_separator: <!--more-->

disqus: nickcraver

google_analytics_ua: UA-28897355-1

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
